lab_app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'lab_reports#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :lab_reports, except: :show
end

lab_app/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab_app/app/models/lab_report.rb
# frozen_string_literal: true

class LabReport < ApplicationRecord
  belongs_to :user
  validates :title, length: { presence: true, minimum: 1, maximum: 250, allow_blank: false }
  validates :description, length: { maximum: 500 }
  accepts_nested_attributes_for :user, allow_destroy: true
end

lab_app/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend Enumerize

  enumerize :role, in: %i[member manager admin], default: :member
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :lab_reports, dependent: :destroy
  validates :first_name, length: { minimum: 1, maximum: 100, allow_blank: false }
  validates :last_name, length: { minimum: 1, maximum: 100, allow_blank: false }
  validates :email, uniqueness: true, length: { minimum: 6, maximum: 100 }
end

lab_app/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionPolicy::Behaviour
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name password_confirmation role])
  end
end

lab_app/app/controllers/lab_reports_controller.rb
# frozen_string_literal: true

class LabReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lab_reports = authorized_scope(LabReport.all)
  end

  def new
    @lab_report = LabReport.new
  end

  def create
    @lab_report = LabReport.new(lab_report_params)
    if @lab_report.save
      flash[:success] = 'Lab report created succesfully!'
      redirect_to lab_reports_path
    else
      render 'new'
    end
  end

  def edit
    @lab_report = LabReport.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Record not found'
    redirect_to lab_reports_path
  end

  def update
    @lab_report = LabReport.find(params[:id])
    authorize! @lab_report

    if @lab_report.update(lab_report_params)
      flash[:success] = 'Lab report was successfuly updated!'
      redirect_to lab_reports_path
    else
      render 'edit'
    end
  rescue ActionPolicy::Unauthorized
    flash[:danger] = 'You are not authorized to this action'
    redirect_to lab_reports_path
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Record not found'
    redirect_to lab_reports_path
  end

  def destroy
    @lab_report = LabReport.find(params[:id])
    @lab_report.destroy
    flash[:success] = 'Lab report has been destroyed!'
    redirect_to lab_reports_path
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Record not found'
    redirect_to lab_reports_path
  end

  private

  def lab_report_params
    params.require(:lab_report).permit(:title, :description, :grade, :user_id)
  end
end

lab_app/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

lab_app/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

lab_app/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

lab_app/app/views/lab_reports/edit.html.haml
%h1 Mark
.row
  .col-md-6.col-md-offset-3
    = form_for @lab_report, local: true do |f|
      = f.label :grade
      = f.select :grade, ["A","B", "C", "D", "E", "FX", "F"]
      - @lab_report.errors.full_messages_for(:title).each do |message|
        %div= message
      = f.submit "mark lab report", class: "btn btn-primary"

lab_app/app/views/lab_reports/index.html.haml
%body
%h1 Welcome to Lab Application!
= link_to "new lab report", new_lab_report_path, class: 'btn btn-warning'
%p
  - @lab_reports.each do |object|
    %h4 #{object.title}
    = object.description
    = button_to "Delete", lab_report_path(object.id), method: :delete, class: 'btn btn-link'
    = link_to "Mark", edit_lab_report_path(object), class: 'btn btn-link'

lab_app/app/views/lab_reports/new.html.haml
%h1 Create new lab report
.row
  .col-md-6.col-md-offset-3
    = form_for @lab_report do |f|
      = f.label :title
      = f.text_field :title
      - @lab_report.errors.full_messages_for(:title).each do |message|
        %div= message

      = f.label :description
      = f.text_field :description
      - @lab_report.errors.full_messages_for(:description).each do |message|
        %div= message

      = f.label :user_id
      = f.collection_select(:user_id, User.all, :id, :email, :prompt => true)

      - @lab_report.errors.full_messages_for(:email).each do |message|
        %div= message
      = f.submit "Create lab report", class: "btn btn-primary"

lab_app/app/views/layouts/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container
    %span.text-muted Alexey Leskov 2022

lab_app/app/views/layouts/_header.html.haml
%body
  %header.p-3.bg-dark.text-white
    .container
      = link_to "Lab App", root_path, id: "logo"
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
          %svg.bi.me-2{:height => "32", :width => "40"}
            %use{"xlink:href" => "#bootstrap"}
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        .text-end
        - if current_user
          = current_user.email
          = button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn-default'
        - else
          = link_to "Login", new_user_session_path, class: 'btn btn-warning'
          = link_to "Sign-up", new_user_registration_path, class: 'btn btn-warning'

lab_app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Test application
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css", :integrity => "sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      = render 'layouts/footer'